### ISSUE TITLE
Sidebar issues

### ISSUE THREAD

**Issue by bj-anas** [youcan-shop/youcan-ui#188]
## Issue Summary

- [x] Can't open a title that has children's if the sidebar is collapsed
- [x] If the sidebar is collapsed and I refresh the page it should stay collapsed
- [x] The active state of a subitem (child title) disappears if it has a related sub-page

## Labels

Enhancement, Bug

**Comment by eihabkhan1** [comment]
+ animation for opening and closing the sidebar items

**Comment by eihabkhan1** [comment]
Issues is handled in this PR https://github.com/youcan-shop/youcan-ui/pull/189
