### ISSUE TITLE
Dropdown not closing after selecting same previous value

### ISSUE THREAD

**Issue by eihabkhan1** [youcan-shop/youcan-ui#279]
## Issue Summary

If I select something in a Dropdown, open it again and then try to select the same thing I chose before, it doesn't close. I have to click outside or click on another value for it to close. Sticky icky yicky.

https://github.com/youcan-shop/youcan-ui/assets/143792300/1905f669-8c01-42ef-8caa-e8e3a0d1d36f

**Comment by mosarabi** [comment]
#281
