### ISSUE TITLE
Dropdown > DropdownItem: Icons don't have a fixed size

### ISSUE THREAD

**Issue by AliHMIMS** [youcan-shop/youcan-ui#287]
## Issue Summary

The icons in the dropdown item don't have a fixed size set in our stylesheet, meaning that those icons will inherit the default sizing set by uno.css.

## Steps to Reproduce

1. Add a DropDown component where the items have icons instead of text only or thumbnail
2. Check the sizing of icons set in your uno.css config
3. The icons size will follow the config instead of having their fixed 20px/20px size

## Expected Behavior

The icons should have a width of `20px` and height of `20px`

## Environment

- **Version:** 2.5.7
- **OS:** MAC OS Sonama 14.1 (23B74)
- **Browser (if applicable):** ARC Version 1.32.0 (46908) | Chromium Engine Version 122.0.6261.94

## Screenshots

<img width="277" alt="image" src="https://github.com/youcan-shop/youcan-ui/assets/85164582/c99192c5-6f0d-418c-aeb5-964fc19c46a1">

## Possible Solution

![image](https://github.com/youcan-shop/youcan-ui/assets/85164582/2e3c1137-a9df-4243-873e-67106ce8b4f8)
Set an explicit sizing for the `preview-icon` class in the `DropdownItem` component.

## Tasks

- [ ] 
- [ ]

## Labels

bug

**Comment by mosarabi** [comment]
The icon size is not a Library issue; it's a design issue.
